### ISSUE TITLE
Unable to receive anything other than 'mentions' from Twitter

### ISSUE THREAD

**Issue by chringel21** [wgroeneveld/go-jamming#1]
I'm self-hosting go-jamming and using https://brid.gy for sending webmentions from silos.

I was successfully able to receive 'mentions' (replies to my tweet), but I can't seem to get any other type ('likes', 'repost', ...), although my tweet received likes and retweets.

brid.gy says it sent the webmention correctly (status 202)

```
D 2022-06-30 08:12:44.908651+00:00 Params: [('response_key', '[agdicmlk...](https://console.cloud.google.com/datastore/entities;kind=Response;ns=__$DEFAULT$__/edit;key=0%252F%257C8%252FResponse%257C45%252Fname%253Atag%253Atwitter.com%252C2013%253A1539131976879308800?project=brid-gy)')]
I 2022-06-30 08:12:44.960286+00:00 Source: DeEgge (Twitter) deegge, https://brid.gy/twitter/deegge
I 2022-06-30 08:12:45.063392+00:00 Created by this poll: https://brid.gy/log?start_time=1656508563&key=agdicmlkLWd5chMLEgdUd2l0dGVyIgZkZWVnZ2UM&module=
I 2022-06-30 08:12:45.063896+00:00 Starting Response repost tag:[twitter.com](http://twitter.com/),2013:1539131976879308800 https://twitter.com/cartocalypse/status/1539131976879308800
I 2022-06-30 08:12:45.064295+00:00 [requests.head](http://requests.head/) https://chringel.dev/2022/06/creating-a-google-maps-clone-part-1-tiles-and-styles/ {'headers': {}}
I 2022-06-30 08:12:45.575933+00:00 Received 200
I 2022-06-30 08:12:45.577934+00:00 Webmention from https://brid.gy/repost/twitter/deegge/1538902082698231808/1539131976879308800 to https://chringel.dev/2022/06/creating-a-google-maps-clone-part-1-tiles-and-styles/
D 2022-06-30 08:12:45.578259+00:00 Webmention discovery: attempting for https://chringel.dev/2022/06/creating-a-google-maps-clone-part-1-tiles-and-styles/
I 2022-06-30 08:12:45.578400+00:00 [requests.get](http://requests.get/) https://chringel.dev/2022/06/creating-a-google-maps-clone-part-1-tiles-and-styles/ {'headers': {}}
I 2022-06-30 08:12:46.144746+00:00 Received 200
D 2022-06-30 08:12:46.246767+00:00 Webmention discovery: got endpoint in tag: https://jam.chringel.dev/webmention
I 2022-06-30 08:12:46.247180+00:00 Sending...
D 2022-06-30 08:12:46.247359+00:00 webmention send: https://brid.gy/repost/twitter/deegge/1538902082698231808/1539131976879308800 -> https://chringel.dev/2022/06/creating-a-google-maps-clone-part-1-tiles-and-styles/
I 2022-06-30 08:12:46.247508+00:00 [requests.post](http://requests.post/) https://jam.chringel.dev/webmention {'data': {'source': 'https://brid.gy/repost/twitter/deegge/1538902082698231808/1539131976879308800', 'target': 'https://chringel.dev/2022/06/creating-a-google-maps-clone-part-1-tiles-and-styles/'}, 'headers': {'User-Agent': '...', 'Accept': '...'}}
I 2022-06-30 08:12:46.946565+00:00 Received 202
D 2022-06-30 08:12:46.946889+00:00 webmention send: got HTTP 202
I 2022-06-30 08:12:46.947072+00:00 Sent! <Response [202]>
I 2022-06-30 08:12:47.039273+00:00 Setting last_webmention_sent
```

Verbose output from go-jamming looks OK as well (don't mind the errors, I haven't set up email notifications):

```
8:12AM INF OK: looks valid wm="source: https://brid.gy/repost/twitter/deegge/1538902082698231808/1539131976879308800, target: https://chringel.dev/2022/06/creating-a-google-maps-clone-part-1-tiles-and-styles/"
8:12AM ERR Failed to save picture. Reverting to anonymous error="Will not save locally because it's form a silo domain" url=https://pbs.twimg.com/profile_images/1115347058750365696/fH1JaiuL.png
8:12AM ERR Failed to notify error="501 Command parsing failed\nError: Syntax error in parameters"
8:12AM INF OK: Webmention processed, in whitelist. key=f7c36139978048dc35e6c2488d918370:chringel.dev 
```

Is there anything I can do to dig into that? Thanks!

**Comment by wgroeneveld** [comment]
Hi,

Thanks for reporting this. Brid.gy is something that to be honest shouldn't exist and I'm far from a fan of how they handle things (mostly privacy-wise). That said, the mention is correct but go-jamming just doesn't know the kind "repost". 

I fixed that in https://github.com/wgroeneveld/go-jamming/commit/4c2326b887c2e13a19d00bb3b8a75e71cfc4d638 

It's not airtight, the h-entry microformat "specification" on https://microformats.org/wiki/h-entry is _very_ open-ended.  A like, bookmark, or repost, appearing as u-like-of, u-bookmark-of, etc should be recognized, I've added your example as a unit test. Again, it's very difficult to parse the "type" as this will depend on where the sender will put it in the microformat in their HTML, it will depend on the m2 parser, etc. I don't think I want a too elaborate implementation for that in go-jamming. It's a bit crude now, but good enough 😀

Does this work for you? Cheers!

**Comment by chringel21** [comment]
Hi Wouter!

> go-jamming just doesn't know the kind "repost"

I almost figured that was the case, and your changes indeed solve the problem, thanks!

May I ask a question:

Where did you get that markup for the unit test https://github.com/wgroeneveld/go-jamming/commit/4c2326b887c2e13a19d00bb3b8a75e71cfc4d638#diff-09775c23802d010f5403b70df91268e4628af432345180ef410e77589782a9ef. Did you write it yourself? Is it kind of a rebuild of what brid.gy parses from a tweet?

Thanks again!

**Comment by wgroeneveld** [comment]
Great to hear it works for you!

The test file is just a grab of your provided bridgy link using `curl https://brid.gy/repost/twitter/deegge/1538902082698231808/1539131976879308800` and saved on disk :-) Since it's more an integration test, I do modify the picture URL as it tries to parse that and the mock server only knows the brainbaking domain.
